name: Deploy to EC2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build image
        run: docker build -t zen00326598/accounting:latest ./accounting
      - name: Push image
        run: docker push zen00326598/accounting:latest
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Deploy with Docker Compose
        run: docker-compose up -d
      - name: Clean up unused images
        run: docker image prune -f